import __init__ as Error
import math
print("Random error message being printed")
number = math.random(1, 15)
